url: http://evo.snu.ac.kr
# baseurl: /home/

# Site settings
title: HNSPB
email: djang@snu.ac.kr
description-en: Human Nature Studies and Philosophy of Biology
description-kr: 서울대학교 인간본성 및 생물철학 연구실


# Team names, titles and social links
people:
- name: 장대익
  pic: no_profile.png
  position: 교수
  major: 진화학 및 과학철학
  social:
    - title: envelope
      url: mailto:djang@snu.ac.kr

- name: 김진영
  pic: no_profile.png
  position: 박사 과정
  major:
  social:
    - title: envelope
      url: mailto:mappaq@hanmail.net

- name: 이형석
  pic: no_profile.png
  position: 박사 과정
  major:
  social:
    - title: envelope
      url: mailto:hyungdralisk@snu.ac.kr

- name: 차영재
  pic: no_profile.png
  position: 박사 과정
  major:
  social:
    - title: envelope
      url: mailto:youngjae.cha@snu.ac.kr

- name: 김창윤
  pic: no_profile.png
  position: 석사 과정
  major:
  social:
    - title: envelope
      url: mailto:cythuskim@gmail.com

- name: 정유희
  pic: no_profile.png
  position: 석사 과정
  major:
  social:
    - title: envelope
      url: mailto:sacrevo@gmail.com

- name: 정지수
  pic: no_profile.png
  position: 석사 과정
  major:
  social:
    - title: envelope
      url: mailto:wltn1126@gmail.com

- name: 김수
  pic: no_profile.png
  position: 학부생
  major:
  social:
    - title: envelope
      url: mailto:carlsagan21@snu.ac.kr

- name: 안민경
  pic: no_profile.png
  position: 학부생
  major:
  social:
    - title: envelope
      url: mailto:grace9071@snu.ac.kr

- name: 신지은
  pic: no_profile.png
  position: 연구원
  major:
  social:
    - title: envelope
      url: mailto:jieunshin00@gmail.com

- name: 구형찬
  pic: no_profile.png
  position: 연구원
  major:
  social:
    - title: envelope
      url: mailto:koohc1@gmail.com

- name: 전진권
  pic: no_profile.png
  position: 박사 졸업생
  major:
  social:
    - title: envelope
      url: mailto:b613jk@hotmail.com

- name: 권오현
  pic: no_profile.png
  position: 석사 졸업생
  major:
  social:
    - title: envelope
      url: mailto:myleetzshe@hanmail.net

- name: 박선진
  pic: no_profile.png
  position: 석사 졸업생
  major:
  social:
    - title: envelope
      url: mailto:maybrian7@gmail.com

- name: 백소정
  pic: no_profile.png
  position: 석사 졸업생
  major:
  social:
    - title: envelope
      url: mailto:sjbaek08@gmail.com

- name: 이민섭
  pic: no_profile.png
  position: 석사 졸업생
  major:
  social:
    - title: envelope
      url: mailto:inermis89@gmail.com

- name: 이보윤
  pic: no_profile.png
  position: 석사 졸업생
  major:
  social:
    - title: envelope
      url: mailto:boyun868@gmail.com


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - 상세주소, 서울대학교, 00동
  - 원생 연구실 주소, 교수님 연구실 주소

# Build settings
markdown: kramdown
permalink: pretty
